name: Deploy
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Install cross
        run: cargo install cross
      - name: Build
        run: cross build --release --target x86_64-unknown-linux-musl
        env:
          GIT_TAG: ${{ steps.tag.outputs.tag }}
          GIT_COMMIT: ${{ github.sha }}
          GIT_REPO: ${{ github.repository }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-unknown-linux-musl/release/makita
          fail_on_unmatched_files: true
