name: Deploy
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Init Rust
        run: rustup toolchain install nightly-2021-10-10-x86_64-unknown-linux-gnu
      - name: Cache
        uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --release
        env:
          GIT_TAG: ${{ steps.tag.outputs.tag }}
          GIT_COMMIT: ${{ github.sha }}
          GIT_REPO: ${{ github.repository }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/makita
          fail_on_unmatched_files: true
