name: Deploy
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
#      - name: Init Rust
#        run: rustup toolchain install x86_64-unknown-linux-musl
#      - name: Build
#        run: cargo build --release
#        env:
#          GIT_TAG: ${{ steps.tag.outputs.tag }}
#          GIT_COMMIT: ${{ github.sha }}
#          GIT_REPO: ${{ github.repository }}
      - name: Build Musl
        uses: stevenleadbeater/rust-musl-builder@master
        with:
          args: '/bin/bash -c "export GIT_TAG=${{ steps.tag.outputs.tag }};
                               export GIT_COMMIT=${{ github.sha }};
                               export GIT_REPO=${{ github.repository }};
                               cargo build --release --target=x86_64-unknown-linux-musl"'
        env:
          GIT_TAG: ${{ steps.tag.outputs.tag }}
          GIT_COMMIT: ${{ github.sha }}
          GIT_REPO: ${{ github.repository }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/makita
          fail_on_unmatched_files: true
